### PR TITLE
Fixed capability typos preventing regenration and delete

### PR DESCRIPTION
**Pull request by szczys**
This addresses #62

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
Thanks for the PR @szczys! This isn't correct though. `delete_post`, `edit_post`, `edit_user` etc... are all valid meta capability checks. AFAIK the issue in #62 is because those meta capability checks aren't being mapped due to how the post type is being registered.

**Comment by szczys** [comment]
Thanks for the info. I'll look into it and see if I can figure out where my install is going wrong with that mapping.

**Comment by TimothyBJacobs** [comment]
To clarify, this isn't a problem specific to your install. It is an issue with the plugin, I'm just not 100% sure what the right fix it.

**Comment by szczys** [comment]
I had certainly noticed some problems here as another plugin that i have installed is throwing warning when parsing these entries:

```
Notice: Trying to get property 'ID' of non-object in /srv/www/wordpress-one/public_html/wp-content/plugins/edit-flow/modules/custom-status/custom-status.php on line 739

Notice: Trying to get property 'label' of non-object in /srv/www/wordpress-one/public_html/wp-content/plugins/edit-flow/modules/custom-status/custom-status.php on line 741
```

**Pull request closed without merging**
